name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '15.x'
      - name: Install dependencies
        run: npm ci
      - name: Run lint:js
        run: npm run lint:js
      - name: Run lint:css
        run: npm run lint:css
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm test
      - name: Deploy
        run: npm run deploy