name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '15.x'
      - name: Install dependencies
        run: npm ci
      - run: npm run lint:js
      - run: npm run lint:css
      - run: npm run build --if-present
      - run: npm test
      - run: npm deploy